### PR TITLE
Use ConfigureAwait(false) on all awaiting tasks

### PR DESCRIPTION
**Pull request by Maxwe11**
There is no sense to return back to the same thread which was initiator of the async operation inside library.

### CODE REVIEW

**Comment by object** [comment]
Thank you for the PR, I merged it but after reading about ConfigureAwait I believe it should not be used in every await case. Read the answer to this question for example:

http://stackoverflow.com/questions/32551534/is-it-advantageous-to-use-configureawaitfalse-in-a-library-that-directly-retur

In short, shouldn't ConfigureAwait be used only on calls that the library needs to await and in case it doesn't need to wait for the result it should run it without configuring await so the caller of the method can choose it's preferred behavior?

**Comment by Maxwe11** [comment]
>I believe it should not be used in every await case

**Comment by Maxwe11** [comment]
>I believe it should not be used in every await case. 

From SO answer which you pointed out:

>Calling ConfigureAwait(false) in library code is best practice only when you await on it in the library

**Comment by Maxwe11** [comment]
>caller of the method can choose it's preferred behavior?

**Comment by Maxwe11** [comment]
> caller of the method can choose it's preferred behavior?

This PR doesn't prevet from choosing prefered behavior.

**Comment by object** [comment]
Makes sense. But I think there a some places that don't need to be awaited at all. Very few,

**Pull request merged**
