### PR TITLE
Custom-Response-Converter (e.g. JSON)

### PR DESCRIPTION
**Pull request by Waldmannstetter**
We need this functionality to convert/deserialize the result (response) very fast.

### CODE REVIEW

**Comment by object** [comment]
Thank you for the pull request. Supporting custom response converters will certainly make the library more flexible. I do however some concerns regarding the implementation (and whether this should be a minor upgrade or a part of the forthcoming version 5.0).

First of all, there are several other methods, not just FindEntriesAsync, that return response, so if the library enables use of custom converters, it should do it for all suitable methods.

Second, we need one or few tests that validate this functionality. Can you give an example of how you use it or a test that can be added to Simple.ODataClient tests?

**Comment by mmierzwa** [comment]
@object do you have any plans to support providing custom converters/serializers to the client lib? Is this possible to do it somehow manually in current implementation?

**Comment by object** [comment]
@mmierzwa Version 5 is more granular, so it's possible to receive plain HttpResponseMessage and apply whatever custom converter to it.

Unfortunately it's going very slow because I no longer actively use OData in my projects, and maintaining something that is no longer in the scope of my regular activities is quite hard.

**Comment by mmierzwa** [comment]
@object I fully understand. I'll try to solve my problem in other way then.

**Comment by object** [comment]
@mmierzwa I released yesterday version 5.0. It better granularity of request/response processing with possibility to inject custom request handles (I use it myself to mock HTTP communication). So I am closing this PR for now and will try to work out an example of custom response converter.

**Pull request closed without merging**
