### PR TITLE
Fix for #371 - Assign to compatible type

### PR DESCRIPTION
**Pull request by phatcher**
This is similar to https://github.com/OData/WebApi/issues/718 so I fixed it in the same way

### CODE REVIEW

**Comment by object** [comment]
Thanks!

**Comment by phatcher** [comment]
@object Any chance of a quick release with this in it?

**Comment by object** [comment]
Probably later tonight or early tomorrow.

**Comment by phatcher** [comment]
Thanks, that will let me get my demo out :-)

**Comment by object** [comment]
I believe it has to be tomorrow morning. I have some pending changes on a different machine.

**Comment by object** [comment]
New version is out.

**Pull request merged**
