### PR TITLE
Fix QueryOption EntityValue validation on CreateInsertRequest

### PR DESCRIPTION
**Pull request by tysonholub**
Found and resolved an issue with the new QueryOption functionality when making a create request. commandText was being passed in to GetQualifiedTypeName with query string appended resulting in a raised UnresolvableObjectException.

### CODE REVIEW

**Comment by object** [comment]
Thank you for the PR. I just merged it to master. I will also apply it to v4 branch that is currently a main branch for V4 NuGet packages.

**Comment by tysonholub** [comment]
I wasn't particularly satisfied with that change either. In fact, I did not intend that commit to be included in the original pull request (this is my first time using GitHub). The issue I was working around was that the implementation of DeleteEntryAsync in ODataClient.Async was building a new FluentCommand object and losing the QueryOptions when doing so. The project I'm working on unfortunately requires me to specify the company I'm running actions against as a QueryOption despite there being an endpoint for Company with navigational properties. So instead of running an action on /Company('CompanyID')/endpoint, I need to do /endpoint?Company=CompanyID (not very restful). This is not a problem with your library but with the OData service I'm consuming.

Anyway, I changed the signature to simply pass the FluentCommand I already had to maintain my QueryOption (and any other properties). This only seemed to be an issue with DeleteEntryAsync and seemed like the fastest workaround for my needs. Maybe a method overload would be more appropriate?

**Comment by object** [comment]
I reverted that commit, so now it's only first one that is applied to master and v4 branches. I didn't fully understand why you need it but can't you just use fluent syntax that is based on FluentCommand. The library has the following API flavours:

1. Basic untyped, built aroud IODataClient - no fluent methods
2. Fluent, untyped
3. Fluent, typed
4. Fluent, dynamic.

The 3 latter use FluentCommand. In fact you changed some tests from using IODataClient to fluen syntax. Can't use just use one of those syntax flavours instead of modifying IODataClient. The problem with modifying it is that it breaks its consistency: what about other methods then, why only Delete? Since this is a generic library, we can't make changes motivated by some specific use case without unifying them across the whole API.

**Comment by tysonholub** [comment]
I thought I was using the fluent syntax. Consider my Delete method
```c#
internal int Delete(string endpoint, string[] keys)
{
    return RunAction(client.For(endpoint).Key(keys).QueryOptions(String.Format("Company={0}", companyId)).DeleteEntriesAsync());
}
```
This will hit ExecuteDeleteEntriesAsync in ODataClient.Internals
```c#
private async Task<int> ExecuteDeleteEntriesAsync(FluentCommand command, CancellationToken cancellationToken)
{
    return await IterateEntriesAsync(
        command,
        async (x, y) => await DeleteEntryAsync(x, y, cancellationToken),
        cancellationToken);
}
```

FluentCommand gets passed to IterateEntriesAsync where we only pass the QualifiedEntityCollectionName into DeleteEntryAsync
```c#
private async Task<int> IterateEntriesAsync(FluentCommand command,
    Func<string, IDictionary<string, object>, Task> funcAsync, CancellationToken cancellationToken)
{
    var collectionName = command.QualifiedEntityCollectionName;
    var commandText = await command.GetCommandTextAsync(cancellationToken);
    if (cancellationToken.IsCancellationRequested) cancellationToken.ThrowIfCancellationRequested();

    var result = 0;
    var client = new ODataClient(_settings);
    var entries = await client.FindEntriesAsync(commandText, cancellationToken);
    if (entries != null)
    {
        var entryList = entries.ToList();
        foreach (var entry in entryList)
        {
            await funcAsync(collectionName, entry);
            if (cancellationToken.IsCancellationRequested) cancellationToken.ThrowIfCancellationRequested();
            ++result;
        }
    }
    
    return result;
}
```

This is where the QueryOptions drop off the Delete request.

**Pull request merged**
