### PR TITLE
Feature/413 inject adapters

### PR DESCRIPTION
**Pull request by nrusitska**
implemented a simple injection mechanism via ODataClientSettings.
an instance of the IAdapterFactory can be assigned and then will be used to create IODataAdapters for the supported protocol versions.

Sample code using this mechanism to inject a custom Adapter that uses a custom serializer to parse the payload for special responses. (Use a custom JSON parser for OData v1-v3 messages)
Assign the Factory
```csharp
var settings = new ODataClientSettings("http://services.odata.org/V3/Northwind/Northwind.svc/");
settings.AdapterFactory = new JsonODataAdapterFactory();
```
How that factory looks like
```csharp
public class JsonODataAdapterFactory : IAdapterFactory
    {
        private static readonly string[] _supportedVersions = { "1.0", "2.0", "3.0" };

        public bool CanLoadForModel(IODataModelAdapter modelAdapter)
        {
            return _supportedVersions.Contains(modelAdapter.ProtocolVersion);
        }

        public IODataAdapter LoadAdapter(ISession session, IODataModelAdapter modelAdapter)
        {
            return new JsonODataAdapter(session, modelAdapter);
        }
    }
```
The simple Adapter inherits from the library's ODataAdapter (V3)
```csharp
public class JsonODataAdapter : ODataAdapter
    {
        private ISession _session;

        public JsonODataAdapter(ISession session, IODataModelAdapter modelAdapter)
            : base(session, modelAdapter)
        {
            _session = session;
        }

        public override IResponseReader GetResponseReader()
        {
            return new JsonResponseReader(_session, Model);
        }
    }
```
And the reader that want's to parse JSON payload by itself. (note, atom payload will be forwarded to the base class)
```csharp
public class JsonResponseReader : ResponseReader
    {
        public JsonResponseReader(ISession session, IEdmModel model) : base(session, model)
        {
        }

        public override Task<ODataResponse> GetResponseAsync(HttpResponseMessage responseMessage)
        {
            var contentHeader = System.Net.Http.Headers.HttpContentHeadersresponseMessage.Content.Headers;

            // only act for JSON payload
            if (contentHeader.ContentType.MediaType == "application/json")
            {
                return Task.Run(async () =>
                {
                    // create an ODataResponse with your custom JSON parser here 
                    // call your serializer (e.g. newtonsoft) and create an ODataResponse from the result
                });
            }
            else
            {
                // no JSON payload => call base method
                return base.GetResponseAsync(responseMessage);
            }
        }
    }
```
Edit: Updated examples to match changed interfaces

### CODE REVIEW

**Comment by object** [comment]
Thank you so much for your work and PR. I am currently struggling with other projects, have almost no time for anything else. Will try to check this out shortly.

**Comment by object** [comment]
Hi Niko,
Sorry for the inconvenience, but after applying the PR #422  from @sixlettervariables (that goes to current version 4) there's a merge conflict in AdapterFactory. The other PR optimized use of cached metadata, and it also touched some of the code you changed. Can you please review the conflict and reissue the PR?
Thanks!

**Comment by nrusitska** [comment]
Hey Vagif,

Sure, it will resolve the issues as soon as I can. 
Best!
Niko

**Comment by sixlettervariables** [comment]
@nrusitska as I'm the one who introduced the conflicts for you, if you need any help let me know!

**Comment by nrusitska** [comment]
Hey folks,
I briefly checked the conflicts and I need to refactor some things to match the changes from #422.
I'm on vacation for a week and will start to fix this when I'm back.
Best regards!
Niko

**Comment by nrusitska** [comment]
Hey folks,

sorry for the long delay - I was captured in some other projects longer than I planned to be.
I've updated my PR to match Christopher's changes.

**Pull request merged**
